from __future__ import annotations

import hashlib
import sys
from pathlib import Path

# Why this exists: the TG1 transfer-guidance tools (2026-09-22) regenerate the benchmark tables,
# the W&B export, encoder dumps, LogME scores and dated cluster dumps. Version the code that
# makes them and ignore what it makes, so none of it can be committed by accident.

TARGET = Path(".gitignore")
ANCHOR = "stale_*/\n"
BLOCK = (
    "stale_*/\n"
    "# tg1 transfer-guidance outputs, regenerated by analysis/build_transfer_benchmark.py,\n"
    "# analysis/wandb_export_by_id.py, analysis/dump_encoder_configs.py and\n"
    "# scripts/score_transferability.py\n"
    "benchmark_*/\n"
    "wandb_by_id.jsonl\n"
    "encoder_configs.tsv\n"
    "tg1_logme_kt_*.jsonl\n"
    "run_inventory_*.tsv\n"
    "inventory_stdout_*.txt\n"
    "sacct_*.txt\n"
    "nodes_gres_*.txt\n"
    "logs_list_*.txt\n"
)


def apply(text: str, old: str, new: str, why: str) -> str:
    # Insertion-style edits keep their anchor, so "old in text" stays true after patching;
    # deciding by containment direction keeps re-runs as no-ops.
    if new in text and (old not in text or old in new):
        print(f"skip (already applied): {why}")
        return text
    n = text.count(old)
    if n != 1:
        sys.exit(f"ABORT ({why}): anchor matched {n} times, expected 1")
    print(f"ok: {why}")
    return text.replace(old, new, 1)


ANCHOR2 = "logs_list_*.txt\n"
BLOCK2 = "logs_list_*.txt\ntg1_logmediag_kt_*.jsonl\n"
ANCHOR3 = "tg1_logmediag_kt_*.jsonl\n"
BLOCK3 = "tg1_logmediag_kt_*.jsonl\ntg1_task2_kt_*.jsonl\ntg1_fewshot_kt_*.jsonl\n"


def main() -> None:
    src = TARGET.read_text(encoding="utf-8")
    out = apply(src, ANCHOR, BLOCK, "ignore tg1 outputs")
    out = apply(out, ANCHOR2, BLOCK2, "ignore tg1 LogME diagnostics")
    out = apply(out, ANCHOR3, BLOCK3, "ignore tg1 Task 2 scores")
    if out != src:
        TARGET.write_text(out, encoding="utf-8")
    print("md5", hashlib.md5(TARGET.read_bytes()).hexdigest())


if __name__ == "__main__":
    main()
